test {
    const testing = @import("std").testing;
    const protocol = @import("protocol.zig");
    const connection = @import("connection.zig");
    testing.refAllDecls(@import("root.zig"));
    testing.refAllDecls(protocol);
    testing.refAllDecls(protocol.CommandFrame);
    testing.refAllDecls(protocol.request_decoder);
    testing.refAllDecls(protocol.request_decoder.Complete);
    testing.refAllDecls(protocol.Resp);
    testing.refAllDecls(protocol.Resp.VTable);
    testing.refAllDecls(protocol.Resp2);
    testing.refAllDecls(protocol.Resp3);
    testing.refAllDecls(protocol.command_encoder);
    testing.refAllDecls(connection);
    testing.refAllDecls(connection.ClientState);
    const aof_loader = @import("persistence/aof_loader.zig");
    testing.refAllDecls(aof_loader);
    testing.refAllDecls(aof_loader.ReplayPolicy);
    _ = @import("protocol/interface_tests.zig");
    _ = @import("protocol/compatibility_tests.zig");
    _ = @import("protocol/resp_command_encoder_tests.zig");
    _ = @import("protocol/request_decoder_tests.zig");
    _ = @import("arity.zig");
    _ = @import("commander_tests.zig");
    _ = @import("commander/hello_tests.zig");
    _ = @import("commander/echo.zig");
    _ = @import("commander/ping.zig");
    _ = @import("commander/dbsize.zig");
    _ = @import("store.zig");
    _ = @import("store/mem_store_tests.zig");
    _ = @import("store/mock_store.zig");
    _ = @import("entry.zig");
    _ = @import("lock.zig");
    _ = @import("storage/default_storage.zig");
    _ = @import("storage/notifier_storage.zig");
    _ = @import("object.zig");
    _ = @import("expiration.zig");
    _ = @import("cron.zig");
    _ = @import("connection/session_tests.zig");
    _ = @import("connection/manager_tests.zig");
    _ = @import("logger/test_logger.zig");
    _ = @import("config.zig");
    _ = @import("config/definition.zig");
    _ = @import("config/registry.zig");
    _ = @import("config/directive_parser.zig");
    _ = @import("config/directive_parser_tests.zig");
    _ = @import("config/builder.zig");
    _ = @import("config/loader.zig");
    _ = @import("config/loader_tests.zig");
    _ = @import("config/input_tests.zig");
    _ = @import("cli.zig");
    _ = @import("cli_tests.zig");
    _ = @import("readiness.zig");
    _ = @import("config_parser_tests.zig");
    _ = @import("persistence/manifest.zig");
    _ = @import("persistence_state_tests.zig");
    _ = @import("persistence/kgc_tests.zig");
    _ = @import("persistence/aof.zig");
    _ = @import("persistence/aof_tests.zig");
    _ = @import("persistence/aof_loader.zig");
    _ = @import("server.zig");
    _ = @import("server_tests.zig");
    _ = @import("persistence_shutdown_tests.zig");
    _ = @import("main.zig");
}
